### PR TITLE
Create a python package

### PR DESCRIPTION
**Pull request by mardiros**
The command is now cxx2rs instead of cxx2rs.py

It also :
- Declare dependencies
- uploadable on pypi

The change in cxx2rs/parser.py is not depending of packaging,
but the example in the README does not work for me without the patch.

### CODE REVIEW

**Comment by manuels** [comment]
Great Job!

Kudos, @mardiros!

**Comment by manuels** [comment]
How do you register this at pypi? Or did you already do this?

**Comment by mardiros** [comment]
I don't.
You need to register on pypi,
Then,

    python setup.py register

Respond to questions,  then

    python setup.py upload

**Comment by manuels** [comment]
I tried that, but `pip install cxx` now fail with

    $ pip install cxx2rs
    Downloading/unpacking cxx2rs
      Downloading cxx2rs-0.1.tar.gz
      Running setup.py egg_info for package cxx2rs
        Traceback (most recent call last):
          File "<string>", line 14, in <module>
          File "/tmp/build/cxx2rs/setup.py", line 11, in <module>
            with open(os.path.join(here, 'README.md')) as readme:
        IOError: [Errno 2] No such file or directory: '/tmp/build/cxx2rs/README.md'
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
    
      File "<string>", line 14, in <module>
    
      File "/tmp/build/cxx2rs/setup.py", line 11, in <module>
    
        with open(os.path.join(here, 'README.md')) as readme:
    
    IOError: [Errno 2] No such file or directory: '/tmp/build/cxx2rs/README.md'
    
    ----------------------------------------
    Command python setup.py egg_info failed with error code 1 in /tmp/build/cxx2rs
    Storing complete log in /home/manuel/.pip/pip.log

**Comment by mardiros** [comment]
I will fix it

**Comment by mardiros** [comment]
See  #6

**Comment by manuels** [comment]
That worked! Thanks!

**Pull request merged**
